DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS PARTICIPANTS;

CREATE TABLE USER(USERNAME VARCHAR(255) PRIMARY KEY NOT NULL, PASSWORD VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), COUNTRY VARCHAR(255));
CREATE TABLE EVENT(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, TITLE VARCHAR(255), LOCATION VARCHAR(255), COUNTRY VARCHAR(255), DESCRIPTION VARCHAR(255));
CREATE TABLE PARTICIPANTS(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, EVENTID INT, PARTICIPANTUSERNAME VARCHAR(255));

/*FOREIGN KEY (EVENTID) REFERENCES public.EVENT(ID)

INSERT INTO USER VALUES('nie', '444', 'ine', 'anon', 'Norway');

INSERT INTO EVENT VALUES(1, 'test', 'oslo', 'Norway', 'some stuff');
INSERT INTO EVENT VALUES(2, 'party', 'berlin', 'Germany', 'das ist god');

INSERT INTO PARTICIPANTS VALUES(1, 1, 'ole');
INSERT INTO PARTICIPANTS VALUES(2, 1, 'loe');
INSERT INTO PARTICIPANTS VALUES(3, 1, 'leo');
INSERT INTO PARTICIPANTS VALUES(4, 2, 'oel');
INSERT INTO PARTICIPANTS VALUES(5, 2, 'eol');
INSERT INTO PARTICIPANTS VALUES(6, 2, 'elo');*/
