DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS EVENT;

CREATE TABLE USER(USERNAME VARCHAR(255) PRIMARY KEY NOT NULL, PASSWORD VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), COUNTRY VARCHAR(255));
CREATE TABLE EVENT(ID INT PRIMARY KEY NOT NULL, TITLE VARCHAR(255), LOCATION VARCHAR(255), COUNTRY VARCHAR(255), DESCRIPTION VARCHAR(255));

INSERT INTO USER VALUES('kari', '444', 'kari', 'bekk', 'Norway');
INSERT INTO USER VALUES('olf', '444', 'ole' 'first', 'Iceland');

INSERT INTO EVENT VALUES(1, 'test', 'oslo', 'Norway', 'some stuff');
INSERT INTO EVENT VALUES(2, 'party', 'berlin', 'Germany', 'das ist god');